### ISSUE TITLE
File Save Locations/Paths unclear

### ISSUE THREAD

**Issue by bodylinksystems** [samiy-xx/keysndr#11]
I really like the program and spent quite a bit of time getting multiple commands set up for DCS (Su-25T). However, I am confused about what is a view, what is a configuration, and what can be scripted.

Further, After removing the old server and installing the new, I lost all of my work. I would liek to have three SETS of screens that I access from one main screen: PREFLIGHT: Flight (nav/ground/air):LAND

I also set up one function to do a number of key combination as one command, and would really rather type a script of these key commands. I am unaware of the format and location where all of this takes place. It seems like there needs to be an overarching "wrapper" or container for views and configs.

Many times the new app just says "Requesting configs" and nothing happens.

running on Nexus 5, Fire tablet 5th Gen and win 8.1 pro pc (under bootcamp)

**Comment by samiy-xx** [comment]
There's a small tutorial on scripting on the wiki. It's a feature that i have not put much effort into yet. Trying to make it better next year :)

"I would like to have three SETS of screens that I access from one main screen"
Thinking of implementing this eventually.

"Many times the new app just says "Requesting configs" and nothing happens."
Sounds like you're launching the legacy android app, which cannot connect to the new server.
Or if using the legacy server, this happends if wifi signal is weak or just planets are not aligned in your favour. The socket code in the legacy version is not very good.

**Comment by samiy-xx** [comment]
The new and old android client actually have the same name "KeySndr" which was not so clever idea (have to fix that later). So, could be that you have them both installed and sometimes launch the wrong version.

**Comment by samiy-xx** [comment]
"I am confused about what is a view, what is a configuration"

A Configuration is a collection of actions, which contain sequences.
There can be grid configurations and view configurations.

Grid configuration is a predefined table layout, 5 colums and 6 rows, where on each of the table cells you can add an action. Only thing needed here is to create the configuration in management portal and then by clicking the cells, add actions and sequences.

View configuration is what ever you want it to be, Create the configuration, actions and sequences in management portal and then create the view for it manually using html, css and javascript.

https://github.com/samiy-xx/keysndr/wiki/Samples
http://keysndr.win/samples.html

**Comment by bodylinksystems** [comment]
I made sure to be using the new version. having both as the same name was confusing. Thank you for the replies. Looks like I will dig into the examples a bit, but I was hoping for a bit more drag and drop, or perhaps some pre-set layouts that I can "populate" with my own actions or string of actions as a stop-gap?

BTW  - Would also like to have a DEFAULT ms value of 250 and be able to COPY actions to create a new one by just changing the key.  i.e., RSHIFT+L power and RALT+L lights

**Comment by samiy-xx** [comment]
Thanks for the input.. I'm planning to implement a lot of features you mentioned eventually. Just focusing at the moment to get everything unit tested and refactoring things that dont make any sense, so i can release a version 1.

The default value might appear soon(tm)
