### ISSUE TITLE
"Media keys" not working

### ISSUE THREAD

**Issue by jacorsca** [samiy-xx/keysndr#22]
For example, create a new grid and add a sequence to an input with a key value of "VolumeDown". Save, press input and it won't work (it will actually print the "c" character in this case).

I only tested with VolumeUp, VolumeDown and MediaPlayPause. I assume it isn't working for other keys of this kind.

**Comment by samiy-xx** [comment]
Yea.. Something is not right. Tried to fix this couple times but no luck so far. I'll get on to it eventually.

**Comment by samiy-xx** [comment]
Tested this a bit and it seems that media keys work on my end (Windows 10) when the process target is something else than desktop, as in, selected from the dropdown list.

Going to release a new version one of these days now which allows to select a process target for each action individually in addition to the configuration level process target.

I'll have to test this a bit first though with some games. As in, can i run a full screen game and briefly send an input to another process while keeping the game full screen.

**Comment by samiy-xx** [comment]
https://github.com/samiy-xx/keysndr/wiki/Media-keys
