### ISSUE TITLE
Commands "running" in server window, but not sent to game (Elite:Dangerous and DCS World)

### ISSUE THREAD

**Issue by bodylinksystems** [samiy-xx/keysndr#23]
KeySndr 1.0.0.38677 (Base lib 1.0.0.38677)

Replicated in both the android app and in chrome browser. DCS does not accept any of KeySndr input

Still unclear if I should build a" grid configuration" or a "view". This is confusing and a real barrier to using your program. I also attempted to change the values of the Elite Dangerous demo template but nothing worked on DC ,(changed target to DCS). Currently just trying to test by open/close the canopy with L-ALT + C

Please provide a simple 4-button screen (two screens that use modifier keys) that can be used to test input times and communication with external applications.

**Comment by bodylinksystems** [comment]
Anyone else having issues with commands not being sent at all?

**Comment by samiy-xx** [comment]
Do you by any chance run DCS World as an admin?

**Comment by bodylinksystems** [comment]
I run both DCS and Elite Dangerous as Admin. I recall there being an issue with where the server was installed and where the profile folders were installed/located? Can the proper locations be worked into the installer?  I also tested running it fullscreen versus borderless with no change in behavior. For E:D, I'm not sure if it's pointing its input at the E:D 64-bit app so I change that in the target and then save before testing. No change in behavior.

I might have mentioned this before, but I really think the entire thing could be simplified by having one thing called a "layout" versus all these configurations and grid configurations.  As it stands it is very confusing, and it keeps me from putting more time into the great software you have built here.

**Comment by Luzifer** [comment]
Same behavior for Elite64 for me…
- Elite not running as Admin
- Elite in fullscreen, borderless or windowed makes no difference
- KeySndr as User / Admin (tested both)
- KeySndr can send events to other windows
- Neither process selected nor foremost window works for Elite

Setup
- KeySndr 1.0.0 (GitHub releases download)
- Windows 10
- Elite Dangerous 64bit without Horizons

**Comment by samiy-xx** [comment]
Try the latest server version.
It seems that i might have done an awkward booboo in an earlier commit :)

**Comment by Luzifer** [comment]
Works for me! 👍  (Borderless Elite)

**Comment by bodylinksystems** [comment]
Limited test (elite throttle mgmnt) worked for me with windowed borderless E:D  :)
